"use client";
import Script from "next/script";
import {useEffect} from "react";
declare global{interface Window{naturable?:Record<string,(...a:any[])=>void>}}
const call=(name:string,...args:any[])=>window.naturable?.[name]?.(...args);
export default function Checker({locale,demo=true}:{locale:"en"|"zh-cn",demo?:boolean}){
 const z=locale==="zh-cn";
 const sample=z?"值得注意的是，人工智能正在赋能各行各业。首先，它可以提升效率；其次，它能够助力创新。此外，有研究表明，这项技术不仅改变了工作方式，更将开启新的篇章。希望这对你有所帮助！":"Great question! In today's digital landscape, experts believe this robust technology is not just a tool, it's a pivotal shift. In order to leverage it, teams could potentially rethink their work. The future looks bright. I hope this helps!";
 useEffect(()=>{window.naturable?.mount?.()},[locale]);
 return <><div className="checker" translate="no">
  <div className="doc-toolbar"><label>{z?"文本语言":"Input language"}<select id="input-language"><option value="auto">{z?"自动识别":"Auto detect"}</option><option value="en">English</option><option value="zh">简体中文 · Beta</option></select></label><label>{z?"写作场景":"Writing purpose"}<select id="purpose" defaultValue="blog"><option value="blog">{z?"博客":"Blog"}</option><option value="email">{z?"邮件":"Email"}</option><option value="marketing">{z?"营销":"Marketing"}</option><option value="general">{z?"通用":"General"}</option><option value="academic">{z?"学术":"Academic"}</option><option value="social">{z?"社交媒体":"Social"}</option><option value="technical">{z?"技术文档":"Technical"}</option></select></label><span id="detected-language" className="meta-pill">—</span><span id="text-count" className="meta-pill">0</span><span id="save-status" className="save-status">{z?"已保存到本地":"Saved locally"}</span></div>
  <div className="stats" id="scores"></div><div id="recheck-summary" className="recheck-summary" hidden></div>
  <div className="editor"><div className="pane"><div className="pane-title"><h3>{z?"你的文本":"Your text"}</h3><span id="dirty-state" className="dirty-state" hidden></span></div><textarea id="input" data-demo={demo?"true":"false"} defaultValue={demo?sample:""} placeholder={z?"粘贴或输入草稿…":"Paste or write your draft…"}/><div className="file-actions"><input id="document-import" className="sr-only" type="file" accept=".txt,.md,.markdown,text/plain,text/markdown" onChange={e=>{const file=e.currentTarget.files?.[0];if(file)call("importDocument",file);e.currentTarget.value="";}}/><button className="file-btn" onClick={()=>document.getElementById("document-import")?.click()}>{z?"导入 TXT / Markdown":"Import TXT / Markdown"}</button><span>{z?"导出":"Export"}</span><button className="file-btn" onClick={()=>call("exportMarkdown")}>Markdown</button><button className="file-btn" onClick={()=>call("exportHtml")}>HTML</button></div><div className="tool-btns"><button id="check-btn" className="btn" onClick={()=>call("analyze")}>{z?"检查":"Check"}</button><button className="btn sec" onClick={()=>call("autofix")}>{z?"一键修复明确问题":"Fix safe issues"}</button><button className="btn sec" onClick={()=>call("loadSample")}>{z?"示例":"Sample"}</button><button className="btn sec" onClick={()=>call("undo")}>{z?"撤销":"Undo"}</button><button className="btn sec" onClick={()=>call("redo")}>{z?"重做":"Redo"}</button><button className="btn sec" onClick={()=>call("copyResult")}>{z?"复制":"Copy"}</button><button className="btn sec" onClick={()=>call("clearText")}>{z?"清空":"Clear"}</button></div></div><div className="pane"><h3>{z?"问题标注":"Highlighted"}</h3><div id="render">{sample}</div></div></div>
  <p id="checker-notice" className="checker-notice" hidden></p><div className="issuesbox" id="issues-panel"><div className="section-title"><h3>{z?"问题与建议":"Writing patterns"}</h3><button className="text-button" onClick={()=>call("restoreIgnored")}>{z?"恢复已忽略项":"Restore ignored"}</button></div><div id="issues"></div></div><div className="issuesbox comparebox" id="compare-panel"><div className="section-title"><h3>{z?"修改对比":"Before / After"}</h3><button className="text-button" onClick={()=>call("copySummary")}>{z?"复制修改摘要":"Copy summary"}</button></div><div id="diff-summary" className="diff-summary"></div><div id="diff-render" className="diff-render"></div></div>
 </div><Script src="/assets/engine.js?v=20260712-p0" strategy="afterInteractive"/></>
}
