export type Locale="en"|"zh-cn";
export const copy={en:{checker:"Editor",how:"How it works",learn:"Blog",pricing:"Pricing",try:"Try free",tag:"Draft never leaves the browser · Blog · Email · Marketing",hero:<>Strip the GPT tone. Keep <em>your</em> voice.</>,lead:"Built for blog posts, emails, and marketing copy. Spot robotic phrasing, fix it in place — your draft never leaves the browser. English or 简体中文.",cta:"Check your text",privacy:"Your draft never leaves the browser. Nothing is uploaded to the cloud.",footer:"Blog, email, and marketing copy — human tone, local privacy.",trust:"Draft never leaves the browser. For blog writers, email marketers, and copy teams."},"zh-cn":{checker:"文本编辑",how:"如何使用",learn:"博客",pricing:"价格",try:"免费试用",tag:"草稿不离开浏览器 · 博客 · 邮件 · 营销",hero:<>给博客 / 邮件 / 营销稿去 GPT 味 — <em>草稿不离开浏览器</em></>,lead:"在浏览器里标出套话和僵硬结构，边改边对比。专为博客、邮件、营销稿；草稿不离开浏览器，文本不上传。",cta:"开始检查",privacy:"草稿不离开浏览器：文本不上云，只留在当前设备。",footer:"博客、邮件、营销稿 — 去 GPT 味，本地隐私。",trust:"草稿不离开浏览器。面向博客作者、邮件营销与文案团队。"}};
export const pages={
 en:{
  "how-it-works":{title:"How Naturable works",body:<><p>The free editor runs deterministic English and Chinese rule packs in your browser.</p><h2>Check, edit, compare, recheck</h2><p>Every issue has a stable rule, severity, confidence, explanation, and suggestion. Only high-confidence changes that preserve meaning can be applied automatically.</p><h2>Naturalness score</h2><p>The score combines clarity, specificity, rhythm, structure, and assistant artifacts. It is heuristic writing guidance, not an AI authorship probability.</p><h2>Privacy</h2><p>Your draft, baseline, diff, and local history never leave your browser.</p></>},
  pricing:{title:"Free to start",body:<><p>Checking, editing, comparing, and rechecking are free and unlimited.</p><h2>Free — $0</h2><ul><li>English rules and Chinese Beta</li><li>Naturalness dimensions and sentence rhythm</li><li>Per-issue controls and safe fixes</li><li>Local drafts, diff, undo, and redo</li></ul><h2>Pro</h2><p>Semantic rewriting and voice tools are still being tested and are not open for purchase.</p></>},
  about:{title:"Writing should sound like a person",body:<><p>Naturable helps writers find mechanical, generic, and templated expression while keeping control of every edit.</p><h2>What we believe</h2><ul><li>Clarity over tricks.</li><li>Privacy by default.</li><li>Honest guidance instead of detector guarantees.</li></ul></>},
  privacy:{title:"Privacy Policy",body:<><p>Free checks run entirely in your browser. Draft text, baselines, and diffs are not uploaded.</p><h2>Language adaptation</h2><p>Cloudflare uses the request country to choose a default language. A locale cookie remembers your manual choice.</p><h2>Rule feedback</h2><p>If you mark a suggestion as helpful, a false positive, or unclear, Naturable sends only the feedback type, rule ID, language, writing purpose, severity, confidence, and engine version. Feedback never includes your original text, matched fragment, revision, diff, draft name, text hash, surrounding context, or content-length signals.</p><p>Feedback is aggregated by rule ID, language, and writing purpose. It identifies rules for review but never changes a live rule automatically; changes require review against a fixed test set.</p><h2>Analytics</h2><p>Product events may include language, purpose, rule ID, category, and coarse count buckets. They never include your text, matched fragments, or diff.</p><p>Questions: privacy@naturable.app</p></>},
  terms:{title:"Terms of Service",body:<><p>Naturable is a writing-assistance tool. You are responsible for the content you edit and how you use the output.</p><h2>No detector guarantee</h2><p>Scores and suggestions are heuristic guidance. Naturable does not guarantee an outcome against any detector, grader, or reviewer.</p><h2>Your text</h2><p>You retain all rights to the text you submit and the output you receive.</p></>},
  learn:{title:"AI writing, explained clearly",body:<><p>Practical guides to clearer, more specific, more natural writing.</p><h2><a href="/en/learn/how-to-remove-ai-tells/">How to remove AI writing tells</a></h2><p>A checklist across vocabulary, sentence patterns, structure, evidence, and rhythm.</p><h2><a href="/en/learn/what-is-perplexity-and-burstiness/">Perplexity and burstiness</a></h2><p>What these statistics say—and what they cannot prove.</p><h2><a href="/en/learn/do-ai-humanizers-work/">Do AI humanizers work?</a></h2><p>Where rewriting helps, where it fails, and a safer approach.</p></>},
  "learn/how-to-remove-ai-tells":{title:"How to remove AI writing tells",body:<><p>Replace generic vocabulary with concrete actions and evidence. Remove assistant chatter and model disclaimers.</p><h2>Sentence and structure</h2><p>Break repeated openings, formulaic transitions, negative parallelism, and uniform paragraph shapes.</p><h2>Evidence</h2><p>Name sources instead of writing “experts say” or “studies show.” End with a concrete result or next step.</p></>},
  "learn/what-is-perplexity-and-burstiness":{title:"What are perplexity and burstiness?",body:<><p>Perplexity describes how predictable words are to a model. Burstiness describes variation in sentence length and structure.</p><p>Both are useful lenses, not proof of authorship. Better writing comes from specific facts, deliberate wording, and rhythm that follows meaning.</p></>},
  "learn/do-ai-humanizers-work":{title:"Do AI humanizers actually work?",body:<><p>Sometimes, inconsistently. Surface rewriting can remove obvious filler, but it cannot guarantee a detector result.</p><h2>A safer goal</h2><p>Make the writing genuinely clear, specific, and yours. Review each change instead of handing the document to a black box.</p></>}
 },
 "zh-cn":{
  "how-it-works":{title:"Naturable 怎么用",body:<><p>Naturable 会直接在浏览器里检查文本。英文和中文各用一套规则，不会生搬硬套。</p><h2>从发现问题到确认修改</h2><p>先找出不自然的表达，再逐条决定要不要改。改完可以查看前后对比，然后重新检查，看看哪些问题已经解决、哪些还在。</p><h2>自然度评分怎么看</h2><p>评分会综合清晰度、具体程度、句子节奏、文章结构和助手残留。它只用来帮助你改稿，不代表文字由真人或 AI 创作的概率。</p><h2>正文不会上传</h2><p>草稿、修改前版本、对比内容和编辑记录都只保存在你的浏览器里。</p></>},
  pricing:{title:"免费版已经够用",body:<><p>检查、逐条修改、查看对比和重新检查都免费，而且不限次数。</p><h2>免费版 · ¥0</h2><ul><li>英文正式版规则，中文规则 Beta</li><li>自然度评分和句子节奏分析</li><li>逐条处理建议，一键修复明确问题</li><li>本地保存草稿，支持对比、撤销和重做</li></ul><h2>Pro · 内测中</h2><p>我们正在测试更深入的语义润色和个人风格功能，目前还没有开放购买。</p></>},
  about:{title:"好文字，应该读得出你的判断",body:<><p>很多 AI 辅助写作的问题，不是语法错了，而是写得太圆滑、太笼统、太像模板。Naturable 帮你把这些地方找出来，但改不改、怎么改，始终由你决定。</p><h2>我们在意什么</h2><ul><li>先把话说清楚，不玩“过检测”的技巧。</li><li>正文默认留在本地，隐私优先。</li><li>不夸大评分，也不承诺任何检测结果。</li></ul></>},
  privacy:{title:"隐私政策",body:<><p>免费版的检查和修改都在浏览器里完成。你的正文、修改前版本和对比内容不会上传到服务器。</p><h2>为什么会自动选择语言</h2><p>Cloudflare 会根据访问地区推荐中文或英文。你手动切换后，我们会用 Cookie 记住选择，下次不再重复判断。</p><h2>规则反馈</h2><p>当你选择“有帮助”“误报”或“建议不清楚”时，Naturable 只发送反馈类型、规则 ID、语言、写作场景、严重程度、置信度和引擎版本。反馈不会包含原文、命中片段、修改结果、Diff、草稿名称、文本 hash、前后文或任何可用于推测内容长度的数据。</p><p>反馈只按规则 ID、语言和写作场景聚合，用于找出需要人工审核的规则。系统不会根据反馈自动修改线上规则；任何调整都必须结合固定测试集审核。</p><h2>我们会记录什么</h2><p>为了改进产品，我们可能记录所选语言、写作场景、规则编号、问题类型和大致数量，但不会记录正文、命中的句子或修改内容。</p><p>如有疑问，请联系 privacy@naturable.app。</p></>},
  terms:{title:"服务条款",body:<><p>Naturable 是一款写作辅助工具。请只处理你本人创作或有权编辑的内容，并对最终使用方式负责。</p><h2>评分仅供改稿参考</h2><p>自然度评分和修改建议不是鉴定结果。我们不保证文字能通过任何检测器、评分系统或人工审核。</p><h2>文字归你所有</h2><p>你始终保留输入内容和修改结果的相关权利。</p></>},
  learn:{title:"把 AI 辅助写作讲明白",body:<><p>不讲玄学，也不教你钻检测器的空子。这里只讨论怎样把文字写得更清楚、更具体、更像你。</p><h2><a href="/zh-cn/learn/how-to-remove-ai-tells/">怎样改掉明显的“AI 腔”</a></h2><p>从套话、句式、结构、论据和节奏入手，逐项修改。</p><h2><a href="/zh-cn/learn/what-is-perplexity-and-burstiness/">困惑度和句子变化，到底是什么</a></h2><p>这些指标可以提供参考，但不能证明作者是谁。</p><h2><a href="/zh-cn/learn/do-ai-humanizers-work/">AI Humanizer 真的有用吗</a></h2><p>哪些修改确实能改善文字，哪些只是换词游戏。</p></>},
  "learn/how-to-remove-ai-tells":{title:"怎样改掉明显的“AI 腔”",body:<><p>先删掉“值得注意的是”一类空话，再把“赋能、打造、重塑”等宽泛词换成具体动作、事实和结果。</p><h2>别让句子排着队走</h2><p>如果每段都从“首先、其次、此外”开始，或者连续使用“不仅……更……”，读起来就会很像模板。根据内容安排顺序，不必强行凑结构。</p><h2>说清楚依据</h2><p>写“研究表明”或“专家认为”时，要给出能核实的来源。结尾也不必升华，用一个明确结论或下一步行动收住即可。</p></>},
  "learn/what-is-perplexity-and-burstiness":{title:"困惑度和句子变化，到底是什么",body:<><p>困惑度大致反映一段文字对语言模型来说有多好猜；句子变化则观察长短、结构和节奏是否过于整齐。</p><p>这些数据可以提醒你文字是否太平、太顺、太统一，但不能据此判断作者是谁。与其刻意塞生僻词，不如补充具体事实，并让句子跟着内容自然变化。</p></>},
  "learn/do-ai-humanizers-work":{title:"AI Humanizer 真的有用吗",body:<><p>有时能改善可读性，但效果并不稳定。简单换词可以删掉部分套话，却无法保证任何检测结果，还可能把原意改坏。</p><h2>更值得做的事</h2><p>别追着检测分数跑。把事实写具体，把判断说清楚，再逐条确认每一处修改是否符合你的本意，这比整篇交给黑盒重写更可靠。</p></>}
 }} as const;
