import type {Metadata} from "next";
import {notFound} from "next/navigation";
import Checker from "@/components/Checker";
import {Header,Footer} from "@/components/SiteShell";
import {copy,pages,type Locale} from "@/lib/content";
import {HowPage,PricingPage,LearnPage} from "@/components/ContentPages";
import {BlogArticlePage,BlogIndexPage,getBlogArticle} from "@/components/Blog";
const locales:Locale[]=["en","zh-cn"];
const articleSlugs=["remove-ai-writing-style","how-to-remove-ai-tells","what-is-perplexity-and-burstiness","do-ai-humanizers-work","common-patterns-in-chinese-ai-copy","make-a-stiff-email-more-direct","replace-claims-with-evidence"];
const slugs=["", "app","how-it-works","pricing","about","privacy","terms","learn",...articleSlugs.map(slug=>`learn/${slug}`)];
const descriptions:Record<Locale,Record<string,string>>={
  en:{"":"Naturable helps blog, email, and marketing writers remove GPT-ish tone locally. No cloud upload. No sign-up.",app:"Edit blog, email, and marketing drafts locally. Strip GPT-ish tone with clear fixes — no cloud upload.","how-it-works":"See how Naturable identifies writing patterns, explains suggestions, and helps you revise without hiding the editing process.",pricing:"Compare Naturable Free and Pro features for private, explainable writing revision.",learn:"Naturable Blog covers AI writing patterns, humanizers, perplexity and burstiness, Chinese AI copy, professional email, and evidence-based marketing."},
  "zh-cn":{"":"给博客、邮件、营销稿去 GPT 味。浏览器本地检查，草稿不上云，无需注册。",app:"在本地编辑博客、邮件、营销稿草稿，标出套话并边改边对比；文本不上云。","how-it-works":"了解 Naturable 如何发现表达问题、解释修改建议，并保留清晰可控的修改过程。",pricing:"比较 Naturable 免费版与专业版的自然表达检查功能。",learn:"Naturable 博客关注 AI 写作修改、中文 AI 文案、困惑度与句子节奏、商务邮件和证据型营销写作。"}
};
const routePath=(locale:string,key:string)=>`/${locale}/${key?`${key}/`:""}`;
export function generateStaticParams(){return locales.flatMap(locale=>slugs.map(slug=>({locale,slug:slug?slug.split("/"):undefined})))}
export async function generateMetadata({params}:{params:Promise<{locale:string;slug?:string[]}>}):Promise<Metadata>{const {locale,slug}=await params;const key=(slug||[]).join("/");const l=locale as Locale;const article=key.startsWith("learn/")?getBlogArticle(l,key.slice(6)):null;const item=key&&key!=="app"?(pages[l] as any)?.[key]:null;const title=article?.title||(key==="learn"?(l==="zh-cn"?"自然写作与 AI 文本修改博客":"Natural Writing and AI Editing Blog"):item?.title)||(key==="app"?(l==="zh-cn"?"自然写作编辑器 — 博客 / 邮件 / 营销稿":"Natural Writing Editor — Blog, Email & Marketing"):(!key?(l==="zh-cn"?"给博客 / 邮件 / 营销稿去 GPT 味 — 草稿不上云":"Strip AI Writing Style | Local & Private for Blog, Email & Marketing"):copy[l]?.footer))||"Naturable";const description=article?.description||descriptions[l]?.[key]||item?.description||descriptions[l]?.[""];const canonical=routePath(locale,key);return {title,description,keywords:article?.keywords,alternates:{canonical,languages:{en:routePath("en",key),"zh-CN":routePath("zh-cn",key),"x-default":routePath("en",key)}},openGraph:{title,description,url:canonical,siteName:"Naturable",locale:l==="zh-cn"?"zh_CN":"en_US",type:article?"article":"website",publishedTime:article?(article.datePublished||"2026-07-12"):undefined,modifiedTime:article?(article.dateModified||article.datePublished||"2026-07-12"):undefined},robots:{index:true,follow:true}}}
export default async function LocalePage({params}:{params:Promise<{locale:string;slug?:string[]}>}){const {locale,slug}=await params;if(!locales.includes(locale as Locale))notFound();const l=locale as Locale,c=copy[l],key=(slug||[]).join("/");let content:React.ReactNode;if(!key){content=<><section className="hero wrap"><span className="tag-note">{c.tag}</span><h1>{c.hero}</h1><p className="lead">{c.lead}</p><div className="cta"><a className="btn" href="#checker">{c.cta}</a><a className="btn sec" href={`/${l}/how-it-works/`}>{c.how}</a></div><div className="trust">{c.trust}</div></section><section id="checker" className="wrap"><Checker locale={l} demo/></section><section className="wrap center"><h2 className="sec-title">{l==="zh-cn"?"清楚、透明、可控":"Clarity you can trust"}</h2><div className="cards"><div className="feat"><h3>{l==="zh-cn"?"本地隐私 · 不上云":"Private by default"}</h3><p>{c.privacy}</p></div><div className="feat"><h3>{l==="zh-cn"?"专为博客、邮件与营销稿":"For blog, email & marketing"}</h3><p>{l==="zh-cn"?"写作场景默认博客，其次邮件与营销，让日常发出的文案更自然。":"Purpose defaults to Blog — then Email and Marketing — so everyday shipping copy stays natural."}</p></div><div className="feat"><h3>{l==="zh-cn"?"从检查到复查":"Complete workflow"}</h3><p>{l==="zh-cn"?"标出套话、边改边对比、再检查一遍。":"Spot robotic phrasing, fix in place, compare, and recheck."}</p></div></div></section></>}else if(key==="app"){content=<main className="wrap shell-main"><h1>{l==="zh-cn"?"自然写作编辑器":"Natural writing editor"}</h1><p className="muted">{l==="zh-cn"?"检查 → 修改 → 对比 → 复查。专为博客、邮件、营销稿 — 免费、本地、不上云。":"Check → edit → compare → recheck. Tuned for blog, email, and marketing — free, private, entirely local."}</p><Checker locale={l}/></main>}else if(key==="how-it-works"){content=<HowPage locale={l}/>}else if(key==="pricing"){content=<PricingPage locale={l}/>}else if(key==="learn"){content=<BlogIndexPage locale={l}/>}else if(key.startsWith("learn/")){const article=getBlogArticle(l,key.slice(6));if(!article)notFound();content=<BlogArticlePage locale={l} article={article}/>}else{const item=(pages[l] as any)[key];if(!item)notFound();content=<main className="wrap shell-main"><article className="prose"><h1>{item.title}</h1>{item.body}<div className="content-actions"><a className="btn" href={`/${l}/app/`}>{c.try}</a></div></article></main>}return <><Header locale={l}/>{content}<Footer locale={l}/></>}
