import type {Metadata} from "next";
import {notFound} from "next/navigation";
import Checker from "@/components/Checker";
import {Header,Footer} from "@/components/SiteShell";
import {copy,pages,type Locale} from "@/lib/content";
import {HowPage,PricingPage,LearnPage} from "@/components/ContentPages";
import {BlogArticlePage,BlogIndexPage,getBlogArticle} from "@/components/Blog";
const locales:Locale[]=["en","zh-cn"];
const articleSlugs=["how-to-remove-ai-tells","what-is-perplexity-and-burstiness","do-ai-humanizers-work","common-patterns-in-chinese-ai-copy","make-a-stiff-email-more-direct","replace-claims-with-evidence"];
const slugs=["", "app","how-it-works","pricing","about","privacy","terms","learn",...articleSlugs.map(slug=>`learn/${slug}`)];
const descriptions:Record<Locale,Record<string,string>>={
  en:{"":"Find mechanical writing patterns and revise English or Simplified Chinese drafts privately in your browser.",app:"Check a draft for mechanical writing patterns, review each suggestion, compare changes, and recheck.","how-it-works":"See how Naturable identifies writing patterns, explains suggestions, and helps you revise without hiding the editing process.",pricing:"Compare Naturable Free and Pro features for private, explainable writing revision.",learn:"Naturable Blog covers AI writing patterns, humanizers, perplexity and burstiness, Chinese AI copy, professional email, and evidence-based marketing."},
  "zh-cn":{"":"在浏览器中检查中英文草稿里的机械表达，逐条理解、修改并复查。",app:"检查草稿中的机械表达，逐条查看建议、对比修改并再次检查。","how-it-works":"了解 Naturable 如何发现表达问题、解释修改建议，并保留清晰可控的修改过程。",pricing:"比较 Naturable 免费版与专业版的自然表达检查功能。",learn:"Naturable 博客关注 AI 写作修改、中文 AI 文案、困惑度与句子节奏、商务邮件和证据型营销写作。"}
};
const routePath=(locale:string,key:string)=>`/${locale}/${key?`${key}/`:""}`;
export function generateStaticParams(){return locales.flatMap(locale=>slugs.map(slug=>({locale,slug:slug?slug.split("/"):undefined})))}
export async function generateMetadata({params}:{params:Promise<{locale:string;slug?:string[]}>}):Promise<Metadata>{const {locale,slug}=await params;const key=(slug||[]).join("/");const l=locale as Locale;const article=key.startsWith("learn/")?getBlogArticle(l,key.slice(6)):null;const item=key&&key!=="app"?(pages[l] as any)?.[key]:null;const title=article?.title||(key==="learn"?(l==="zh-cn"?"自然写作与 AI 文本修改博客":"Natural Writing and AI Editing Blog"):item?.title)||(key==="app"?(l==="zh-cn"?"自然表达检查器":"Natural writing editor"):copy[l]?.footer)||"Naturable";const description=article?.description||descriptions[l]?.[key]||item?.description||descriptions[l]?.[""];const canonical=routePath(locale,key);return {title,description,keywords:article?.keywords,alternates:{canonical,languages:{en:routePath("en",key),"zh-CN":routePath("zh-cn",key),"x-default":routePath("en",key)}},openGraph:{title,description,url:canonical,siteName:"Naturable",locale:l==="zh-cn"?"zh_CN":"en_US",type:article?"article":"website",publishedTime:article?"2026-07-12":undefined,modifiedTime:article?"2026-07-12":undefined},robots:{index:true,follow:true}}}
export default async function LocalePage({params}:{params:Promise<{locale:string;slug?:string[]}>}){const {locale,slug}=await params;if(!locales.includes(locale as Locale))notFound();const l=locale as Locale,c=copy[l],key=(slug||[]).join("/");let content:React.ReactNode;if(!key){content=<><section className="hero wrap"><span className="tag-note">{c.tag}</span><h1>{c.hero}</h1><p className="lead">{c.lead}</p><div className="cta"><a className="btn" href="#checker">{c.cta}</a><a className="btn sec" href={`/${l}/how-it-works/`}>{c.how}</a></div></section><section id="checker" className="wrap"><Checker locale={l} demo/></section><section className="wrap center"><h2 className="sec-title">{l==="zh-cn"?"看得懂、改得准、能复查":"Explainable, controlled, verifiable"}</h2><div className="cards"><div className="feat"><h3>{l==="zh-cn"?"隐私优先":"Private by default"}</h3><p>{c.privacy}</p></div><div className="feat"><h3>{l==="zh-cn"?"中英文各有一套规则":"Language-native"}</h3><p>{l==="zh-cn"?"英文按英文习惯检查，中文按中文习惯检查。":"English and Chinese use independent rules."}</p></div><div className="feat"><h3>{l==="zh-cn"?"从检查到复查":"Complete workflow"}</h3><p>{l==="zh-cn"?"发现问题、动手修改、查看对比、再次检查。":"Check, edit, compare, recheck."}</p></div></div></section></>}else if(key==="app"){content=<main className="wrap shell-main"><h1>{l==="zh-cn"?"自然表达检查器":"Natural writing editor"}</h1><p className="muted">{c.lead}</p><Checker locale={l}/></main>}else if(key==="how-it-works"){content=<HowPage locale={l}/>}else if(key==="pricing"){content=<PricingPage locale={l}/>}else if(key==="learn"){content=<BlogIndexPage locale={l}/>}else if(key.startsWith("learn/")){const article=getBlogArticle(l,key.slice(6));if(!article)notFound();content=<BlogArticlePage locale={l} article={article}/>}else{const item=(pages[l] as any)[key];if(!item)notFound();content=<main className="wrap shell-main"><article className="prose"><h1>{item.title}</h1>{item.body}<div className="content-actions"><a className="btn" href={`/${l}/app/`}>{c.try}</a></div></article></main>}return <><Header locale={l}/>{content}<Footer locale={l}/></>}
